import { BlogCardProps } from "./Card";

export const blogData: BlogCardProps[] = [
  {
    id: 1,
    title: "Biodegradable Alternatives: Redefining Consumer Goods",
    category: "Manufacturing",
    image: "/assets/blog1.jpg",
    author: "Eco Innovators",
    date: "12 Sep, 2025",
  },
  {
    id: 2,
    title: "Sustainable Fashion: The Future of Textile Industry",
    category: "Fashion",
    image: "/assets/blog2.jpg",
    author: "Style Green",
    date: "05 Sep, 2025",
  },
  {
    id: 3,
    title: "AI in Healthcare: Transforming Patient",
    category: "Technology",
    image: "/assets/blog3.jpg",
    author: "HealthTech Lab",
    date: "22 Aug, 2025",
  },
  {
    id: 4,
    title: "Renewable Energy Trends to Watch in 2025",
    category: "Energy",
    image: "/assets/blog1.jpg",
    author: "Power Vision",
    date: "18 Aug, 2025",
  },
  {
    id: 5,
    title: "Biodegradable Alternatives: Redefining Consumer Goods",
    category: "Manufacturing",
    image: "/assets/blog2.jpg",
    author: "Eco Innovators",
    date: "12 Sep, 2025",
  },
  {
    id: 6,
    title: "Sustainable Fashion: The Future of Textile Industry",
    category: "Fashion",
    image: "/assets/blog3.jpg",
    author: "Style Green",
    date: "05 Sep, 2025",
  },
  {
    id: 7,
    title: "AI in Healthcare: Transforming Patient Experience",
    category: "Technology",
    image: "/assets/blog1.jpg",
    author: "HealthTech Lab",
    date: "22 Aug, 2025",
  },
  {
    id: 8,
    title: "Renewable Energy Trends to Watch in 2025",
    category: "Energy",
    image: "/assets/blog2.jpg",
    author: "Power Vision",
    date: "18 Aug, 2025",
  },
  {
    id: 9,
    title: "Biodegradable Alternatives: Redefining Consumer Goods",
    category: "Manufacturing",
    image: "/assets/blog3.jpg",
    author: "Eco Innovators",
    date: "12 Sep, 2025",
  },
  {
    id: 10,
    title: "Sustainable Fashion: The Future of Textile Industry",
    category: "Fashion",
    image: "/assets/blog1.jpg",
    author: "Style Green",
    date: "05 Sep, 2025",
  },
  {
    id: 11,
    title: "AI in Healthcare: Transforming Patient Experience",
    category: "Technology",
    image: "/assets/blog2.jpg",
    author: "HealthTech Lab",
    date: "22 Aug, 2025",
  },
  {
    id: 12,
    title: "Renewable Energy Trends to Watch in 2025",
    category: "Energy",
    image: "/assets/ski-image.jpg",
    author: "Power Vision",
    date: "18 Aug, 2025",
  },
];
