export const PRODUCTS = [
  {
    id: "ecc-1020",
    title: "ECC 1020",
    imageSrc: "/assets/products/product1.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "Everclear CO2 Extrusion",
  },
  {
    id: "ec-3010-transparent-white",
    title: "EC 3010 transparent & white",
    imageSrc: "/assets/products/product1.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "Everclear CO2 Extrusion",
  },
  {
    id: "ecc-4060",
    title: "ECC 4060",
    imageSrc: "/assets/products/product1.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "Everclear CO2 Extrusion",
  },
  {
    id: "p-tex-2000-electra",
    title: "P-tex® 2000 electra",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-2000-hc-high-clear",
    title: "P-tex® 2000 HC high clear",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-2100-black",
    title: "P-tex® 2100 black",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-3000-colored",
    title: "P-tex® 3000 colored",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-3000-white",
    title: "P-tex® 3000 white",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-3000-black",
    title: "P-tex® 3000 black",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-3000-clear",
    title: "P-tex® 3000 clear",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-4082-black",
    title: "P-tex® 4082 black",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-4504-black",
    title: "P-tex® 4504 black",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-5188-black",
    title: "P-tex® 5188 black",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-5480-black",
    title: "P-tex® 5480 black",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-5920-black",
    title: "P-tex® 5920 black",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: "p-tex-xc",
    title: "P-tex® XC",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: "p-tex-1820-clear",
    title: "P-tex® 1820 clear",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: "p-tex-1820-black",
    title: "P-tex® 1820 black",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: "p-tex-1100-black",
    title: "P-tex® 1100 black",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: "p-tex-900-htr",
    title: "P-tex® 900 HTR",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: "p-tex-800-clear-colored",
    title: "P-tex® 800 clear & colored",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: "tp-455-black-white",
    title: "TP 455 black & white",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: "tp190",
    title: "TP190",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: "abs-extrusions",
    title: "ABS extrusions",
    subtitle: "Extrusion Films",
    imageSrc: "/assets/products/product2.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "ABS panels",
  },
  {
    id: "abs-profiles",
    title: "ABS profiles",
    subtitle: "Extrusion Films",
    imageSrc: "/assets/products/product2.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "ABS panels",
  },
  {
    id: "pe-1000",
    title: "PE 1000",
    imageSrc: "/assets/products/product3.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "PE 1000 strapping materials",
  },
  {
    id: "t-series-natural",
    title: "T-series natural",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: "t-series-uv-natural",
    title: "T-series UV natural",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: "c-series",
    title: "C-series",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: "f-series",
    title: "F-series",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: "fc-series",
    title: "FC-series",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: "w-series",
    title: "W-series",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: "umc-series",
    title: "UMC series",
    imageSrc: "/assets/products/product2.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "Unic Film thin films",
  },
  {
    id: "pa6-6",
    title: "PA6.6",
    imageSrc: "/assets/products/product2.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "Technical Products",
  },
  {
    id: "pps",
    title: "PPS",
    imageSrc: "/assets/products/product2.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "Technical Products",
  },
  {
    id: "pla-pbs-pbat-biobased",
    title: "PLA / PBS / PBAT (Biobased)",
    imageSrc: "/assets/products/product2.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "Technical Products",
  },
];
