export const PRODUCTS = [
  {
    id: 1,
    title: " ECC 1020",
    imageSrc: "/assets/products/product1.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "Everclear CO2 Extrusion",
  },
  {
    id: 2,
    title: "EC 3010 transparent & white",
    imageSrc: "/assets/products/product1.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "Everclear CO2 Extrusion",
  },
  {
    id: 3,
    title: " ECC 4060",
    imageSrc: "/assets/products/product1.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "Everclear CO2 Extrusion",
  },
  {
    id: 4,
    title: "P-tex® 2000 electra",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: 5,
    title: "P-tex® 2000 HC high clear",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: 6,
    title: "P-tex® 2100 black",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: 7,
    title: "P-tex® 3000 colored",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: 8,
    title: "P-tex® 3000 white",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: 9,
    title: "P-tex® 3000 black",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: 10,
    title: "P-tex® 3000 clear",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: 11,
    title: "P-tex® 4082 black",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: 12,
    title: "P-tex® 4504 black",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: 13,
    title: "P-tex® 5188 black",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: 14,
    title: "P-tex® 5480 black",
    imageSrc: "/assets/products/product2.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "P-tex® UHMWPE",
  },
  {
    id: 15,
    title: "P-tex® 5920 black",
    imageSrc: "/assets/products/product3.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "P-tex® UHMWPE",
  },
  {
    id: 16,
    title: "P-tex® XC",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: 17,
    title: "P-tex® 1820 clear",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: 18,
    title: "P-tex® 1820 black",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: 19,
    title: "P-tex® 1100 black",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: 20,
    title: "P-tex® 900 HTR",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: 21,
    title: "P-tex® 800 clear & colored",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: 22,
    title: "TP 455 black & white",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: 23,
    title: "TP190",
    imageSrc: "/assets/products/product1.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "P-tex® HDPE",
  },
  {
    id: 24,
    title: "ABS extrusions",
    subtitle: "Extrusion Films",
    imageSrc: "/assets/products/product2.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "ABS panels",
  },
  {
    id: 25,
    title: "ABS profiles",
    subtitle: "Extrusion Films",
    imageSrc: "/assets/products/product2.svg",
    material: "High-clarity Polymer",
    thicknessRange: "25µm – 150µm",
    applications: "Packaging, Protective Films, Technical Uses",
    category: "ABS panels",
  },
  {
    id: 26,
    title: "PE 1000",
    imageSrc: "/assets/products/product3.svg",
    material: "Acrylonitrile Butadiene Styrene",
    applications: "Versatile, strong, easy to use | Applications: Automotive, Construction, Consumer Goods",
    category: "PE 1000 strapping materials",
  },
  {
    id: 27,
    title: "T-series natural",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: 28,
    title: "T-series UV natural",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: 29,
    title: "C-series",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: 30,
    title: "F-series",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: 31,
    title: "FC-series",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: 32,
    title: "W-series",
    imageSrc: "/assets/products/product1.svg",
    material: "Ultra-High-Molecular-weight Polyethylene",
    thicknessRange: "Density: 0.93 – 0.96 g/cm³",
    applications: "Wear Plates, Liners, Industrial Components",
    category: "Unic Film thin films",
  },
  {
    id: 33,
    title: "UMC series",
    imageSrc: "/assets/products/product2.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "Unic Film thin films",
  },
  {
    id: 34,
    title: "PA6.6",
    imageSrc: "/assets/products/product2.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "Technical Products",
  },
  {
    id: 35,
    title: "PPS",
    imageSrc: "/assets/products/product2.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "Technical Products",
  },
  {
    id: 36,
    title: "PLA / PBS / PBAT (Biobased)",
    imageSrc: "/assets/products/product2.svg",
    material: "Renewable-source Polymers",
    applications: "Features: Eco-friendly | Applications: Eco-packaging, Green Engineering Solutions",
    category: "Technical Products",
  }
];
